export const BridgeCurrency = {
    BTC: "BTC",
    BCH: "BCH",
    DOTS: "DOTS",
    DOGE: "DOGE",
    ZEC: "ZEC",
    DGB: "DGB",
    LUNA: "LUNA",
    FIL: "FIL",
    RENBTC: "RENBTC",
    RENBCH: "RENBCH",
    RENDOGE: "RENDOGE",
    RENZEC: "RENZEC",
    RENDGB: "RENDGB",
    RENLUNA: "RENLUNA",
    RENFIL: "RENFIL",
    ETH: "ETH",
    FTM: "FTM",
    MATIC: "MATIC",
    BNB: "BNB",
    AVAX: "AVAX",
    SOL: "SOL",
    ARBETH: "ARBETH",
    UNKNOWN: "UNKNOWN",
}